# Generated by Django 4.2.6 on 2023-10-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_rename_cinema_anime_alter_anime_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка видио'),
        ),
    ]
