# Generated by Django 4.2.6 on 2023-11-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
